<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $recipe['recipeName'] }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #333; }
        .container { padding: 20px; }
        .recipe-image { width: 100%; height: 250px; object-fit: cover; margin-bottom: 20px; border-radius: 8px; }
        h1 { font-size: 28px; text-align: center; margin-bottom: 10px; color: #16a34a; }
        .description { text-align: center; font-style: italic; color: #555; margin-bottom: 25px; }
        .details-grid { border: 1px solid #ddd; padding: 15px; margin-bottom: 25px; border-radius: 8px; }
        .details-grid table { width: 100%; }
        .details-grid td { text-align: center; padding: 5px; }
        .section-title { font-size: 22px; color: #16a34a; border-bottom: 2px solid #16a34a; padding-bottom: 5px; margin-top: 30px; margin-bottom: 15px; }
        ul, ol { padding-left: 20px; }
        li { margin-bottom: 8px; line-height: 1.5; }
        .footer { text-align: center; margin-top: 40px; font-size: 12px; color: #888; }
    </style>
</head>
<body>
    <div class="container">
        <h1>{{ $recipe['recipeName'] }}</h1>
        <p class="description">{{ $recipe['description'] }}</p>

        @if (!empty($imageUrl))
            <img src="{{ $imageUrl }}" alt="Recipe Image" class="recipe-image">
        @endif

        <div class="details-grid">
            <table>
                <tr>
                    <td><strong>Time:</strong> {{ $recipe['cookingTime'] }}</td>
                    <td><strong>Calories:</strong> {{ $recipe['calories'] }}</td>
                    <td><strong>Difficulty:</strong> {{ $recipe['difficulty'] }}</td>
                    <td><strong>Cuisine:</strong> {{ $recipe['cuisine'] }}</td>
                    <td><strong>Servings:</strong> {{ $recipe['servings'] }}</td>
                </tr>
            </table>
        </div>

        <h2 class="section-title">Ingredients</h2>
        <ul>
            @foreach ($recipe['ingredients'] as $ingredient)
                <li>{{ $ingredient }}</li>
            @endforeach
        </ul>

        <h2 class="section-title">Instructions</h2>
        <ol>
            @foreach ($recipe['instructions'] as $instruction)
                <li>{{ $instruction }}</li>
            @endforeach
        </ol>

        <p class="footer">
            Generated by SmartChef AI | {{ date('Y-m-d') }}
        </p>
    </div>
</body>
</html>